experiment: 
  name: default
  ema_alpha: 0.98

model: 
  name: Autoencoder
  blocks:
    - 32
    - 64
    - 64
  layers_per_block: 1
  bottleneck_dim: 128
  skip_connections: True
  use_skip_convs: False
  residual: False

  activation: ReLU
  bn: True
  grayscale: False


augmentation: weak2

optimizer:
  name: Adam
  lr: 0.002
  weight_decay: 0.0001

scheduler:
  name: ReduceLROnPlateau
  factor: 0.2
  min_lr: 0.00001
  patience: 20
  cooldown: 30
  threshold: 0.005
  verbose: True
  

batch_size: 256

loss: Kaggle