experiment: 
  name: default
  ema_alpha: 0.98

model: 
  name: SimpleAutoencoder

optimizer:
  name: Adam
  lr: 0.005

scheduler:
  name: ReduceLROnPlateau
  factor: 0.1
  patience: 15
  threshold: 0.01
  min_lr: 0.00001
  verbose: True
  

batch_size: 128