experiment: 
  name: default
  ema_alpha: 0.98

model: 
  name: SimpleAutoencoder
  single_channel: False

optimizer:
  name: Adam
  lr: 0.002
  weight_decay: 0.001

scheduler:
  name: ReduceLROnPlateau
  factor: 0.2
  patience: 15
  threshold: 0.005
  min_lr: 0.00001
  verbose: True
  

batch_size: 128