experiment: 
  name: domain_adaptation
  ema_alpha: 0.98

model: 
  name: Autoencoder
  blocks:
    - 64
    - 128
    - 256
    - 256
  layers_per_block: 2
  bottleneck_dim: 256
  skip_connections: True
  use_skip_convs: False
  residual: True
  
  activation: ReLU
  bn: True
  grayscale: False

augmentation: 
  name: weak2
  strength: 0.6
  proportion: 1.0 # since we do this manually for the dom. adaptation

optimizer:
  name: Adam
  lr: 0.001
  weight_decay: 0.01

scheduler:
  name: ExponentialLR
  gamma: 0.999
  

batch_size: 256

loss: Kaggle

domain_adaptation:
  aug_threshold: 0.5 # probability that training sample gets augmented
  dom_lambda: 0.1 # weight for the domain classification loss