experiment: 
  name: default
  ema_alpha: 0.99

model: 
  name: RefineNet
  blocks:
    - 128
    - 256
    - 256
    - 256
  layers_per_block: 2
  bottleneck_dim: 256
  skip_connections: True
  use_skip_convs: False
  less_skips: True
  
  activation: ReLU


augmentation: 
  name: weak3
  strength: 0.6
  proportion: 0.8

optimizer:
  name: Adam
  lr: 0.001
  weight_decay: 0.01

scheduler:
  name: ExponentialLR
  gamma: 0.999
  

batch_size: 128

loss:
  name: Bootstrap
  p: 0.25
  
