experiment: 
  name: default
  ema_alpha: 0.98

model: 
  name: DictionaryAutoencoder


augmentation: identity

optimizer:
  name: Adam
  lr: 0.001
  weight_decay: 0.01

scheduler:
  name: ExponentialLR
  gamma: 0.995
  

batch_size: 256

loss: Kaggle